import { CategorySchema } from './types';

export const genericProcurementSchema: CategorySchema = {
  id: 'generic',
  name: 'Generic Procurement',
  fields: {
    // ─── SECTION A: PRODUCT OVERVIEW (Intent Layer) ─────────────────────
    'product.name': {
      requirement: 'required',
      label: 'Product Name',
      priority: 'critical',
      layer: 'intent',
      question_template: 'What specific product are you looking to source?',
      default_criticality: 'critical',
    },
    'product.intended_use': {
      requirement: 'required',
      label: 'Intended Use / Application',
      priority: 'critical',
      layer: 'intent',
      question_template: 'What is the primary use case or target market for this product?',
      recommendation_available: true,
      default_criticality: 'critical',
    },
    'product.buyer_segment': {
      requirement: 'optional',
      label: 'Buyer Segment',
      priority: 'medium',
      layer: 'intent',
      question_template: 'Who is the end customer? (e.g., retail, B2B, hospitality, consumer)',
      default_criticality: 'medium',
    },
    'quantity.required_quantity': {
      requirement: 'required',
      label: 'Required Quantity',
      priority: 'critical',
      layer: 'intent',
      question_template: 'What is your target order quantity?',
      buyer_side: true,
      normalize_unit: 'units',
      default_criticality: 'critical',
      description: 'Buyer demand quantity — NOT supplier MOQ',
    },
    'quantity.unit': {
      requirement: 'optional',
      label: 'Unit of Measure',
      priority: 'medium',
      layer: 'intent',
      default_criticality: 'medium',
    },

    // ─── SECTION B: TECHNICAL SPECIFICATIONS ────────────────────────────
    'specifications.material': {
      requirement: 'required',
      label: 'Primary Material',
      priority: 'high',
      layer: 'specification',
      question_template: 'What material should this be made from?',
      recommendation_available: true,
      default_criticality: 'high',
      description: 'Use the most specific material name (e.g., Stoneware not Ceramic)',
    },
    'specifications.material_grade': {
      requirement: 'optional',
      label: 'Material Grade / Subtype',
      priority: 'medium',
      layer: 'specification',
      parent_taxonomy: 'specifications.material',
      default_criticality: 'medium',
      question_template: 'Is there a specific grade or subtype of the material?',
    },
    'specifications.dimensions': {
      requirement: 'recommended',
      label: 'Dimensions',
      priority: 'high',
      layer: 'specification',
      question_template: 'What are the required dimensions?',
      normalize_unit: 'mm',
      default_criticality: 'high',
    },
    'specifications.diameter': {
      requirement: 'optional',
      label: 'Diameter',
      priority: 'high',
      layer: 'specification',
      normalize_unit: 'mm',
      default_criticality: 'medium',
    },
    'specifications.length': {
      requirement: 'optional',
      label: 'Length',
      priority: 'medium',
      layer: 'specification',
      normalize_unit: 'mm',
      default_criticality: 'medium',
    },
    'specifications.width': {
      requirement: 'optional',
      label: 'Width',
      priority: 'medium',
      layer: 'specification',
      normalize_unit: 'mm',
      default_criticality: 'medium',
    },
    'specifications.height': {
      requirement: 'optional',
      label: 'Height',
      priority: 'medium',
      layer: 'specification',
      normalize_unit: 'mm',
      default_criticality: 'medium',
    },
    'specifications.thickness': {
      requirement: 'optional',
      label: 'Thickness',
      priority: 'medium',
      layer: 'specification',
      normalize_unit: 'mm',
      default_criticality: 'medium',
    },
    'specifications.shape': {
      requirement: 'optional',
      label: 'Shape',
      priority: 'medium',
      layer: 'specification',
      default_criticality: 'low',
    },
    'specifications.color': {
      requirement: 'recommended',
      label: 'Color',
      priority: 'high',
      layer: 'specification',
      question_template: 'What color(s) do you need?',
      default_criticality: 'high',
    },
    'specifications.finish': {
      requirement: 'optional',
      label: 'Finish / Surface Treatment',
      priority: 'high',
      layer: 'specification',
      question_template: 'Does this require any specific finish or surface treatment?',
      recommendation_available: true,
      default_criticality: 'medium',
    },
    'specifications.weight': {
      requirement: 'optional',
      label: 'Weight',
      priority: 'high',
      layer: 'specification',
      question_template: 'Is there a target weight per unit?',
      normalize_unit: 'g',
      default_criticality: 'medium',
    },
    'specifications.duty_level': {
      requirement: 'optional',
      label: 'Duty Level',
      priority: 'medium',
      layer: 'specification',
      default_criticality: 'medium',
    },
    'specifications.performance': {
      requirement: 'optional',
      label: 'Performance Requirements',
      priority: 'medium',
      layer: 'specification',
      default_criticality: 'medium',
    },
    'specifications.tolerances': {
      requirement: 'optional',
      label: 'Tolerances',
      priority: 'medium',
      layer: 'specification',
      default_criticality: 'low',
      description: 'Never auto-invent tolerances. Only record if buyer or AI-approved.',
    },
    'specifications.construction': {
      requirement: 'optional',
      label: 'Construction Method',
      priority: 'low',
      layer: 'specification',
      default_criticality: 'low',
    },
    'specifications.technical_standards': {
      requirement: 'optional',
      label: 'Technical Standards',
      priority: 'medium',
      layer: 'specification',
      default_criticality: 'medium',
    },

    // ─── SECTION C: CUSTOMIZATION ───────────────────────────────────────
    'specifications.branding_required': {
      requirement: 'recommended',
      label: 'Branding Required',
      priority: 'medium',
      layer: 'customization',
      question_template: 'Will this product require custom branding or a logo?',
      options: ['yes', 'no'],
      default_criticality: 'medium',
    },
    'specifications.logo_location': {
      requirement: 'optional',
      label: 'Logo Position',
      priority: 'medium',
      layer: 'customization',
      depends_on: { 'specifications.branding_required': ['yes'] },
      skip_when: { 'specifications.branding_required': ['no'] },
      default_criticality: 'low',
    },
    'specifications.logo_size': {
      requirement: 'optional',
      label: 'Logo Size',
      priority: 'low',
      layer: 'customization',
      depends_on: { 'specifications.branding_required': ['yes'] },
      skip_when: { 'specifications.branding_required': ['no'] },
      default_criticality: 'low',
    },
    'specifications.artwork': {
      requirement: 'optional',
      label: 'Artwork Format',
      priority: 'medium',
      layer: 'customization',
      depends_on: { 'specifications.branding_required': ['yes'] },
      skip_when: { 'specifications.branding_required': ['no'] },
      default_criticality: 'low',
    },
    'specifications.decoration_method': {
      requirement: 'optional',
      label: 'Decoration Method',
      priority: 'medium',
      layer: 'customization',
      depends_on: { 'specifications.branding_required': ['yes'] },
      skip_when: { 'specifications.branding_required': ['no'] },
      recommendation_available: true,
      default_criticality: 'low',
    },
    'specifications.oem_odm': {
      requirement: 'optional',
      label: 'OEM/ODM',
      priority: 'low',
      layer: 'customization',
      default_criticality: 'low',
    },
    'specifications.custom_packaging': {
      requirement: 'optional',
      label: 'Custom Packaging',
      priority: 'low',
      layer: 'customization',
      default_criticality: 'low',
    },

    // ─── SECTION D: QUALITY & COMPLIANCE ────────────────────────────────
    'compliance.food_contact': {
      requirement: 'optional',
      label: 'Food Contact Safe',
      priority: 'high',
      layer: 'compliance',
      question_template: 'Will this product come into direct contact with food or beverages?',
      options: ['yes', 'no'],
      default_criticality: 'medium',
      criticality_rules: [
        { when: { 'product.intended_use': ['restaurant', 'food', 'kitchen', 'dining', 'tableware', 'table service'] }, criticality: 'critical' }
      ],
    },
    'compliance.certifications': {
      requirement: 'recommended',
      label: 'Required Certifications',
      priority: 'high',
      layer: 'compliance',
      question_template: 'Are there specific certifications required for your market (e.g., CE, FDA, RoHS)?',
      recommendation_available: true,
      default_criticality: 'medium',
    },
    'compliance.regulatory_requirements': {
      requirement: 'optional',
      label: 'Regulatory Requirements',
      priority: 'high',
      layer: 'compliance',
      default_criticality: 'medium',
    },
    'compliance.testing_requirements': {
      requirement: 'optional',
      label: 'Testing Requirements',
      priority: 'medium',
      layer: 'compliance',
      default_criticality: 'low',
    },
    'quality.inspection_level': {
      requirement: 'recommended',
      label: 'Inspection Level',
      priority: 'high',
      layer: 'quality',
      question_template: 'What level of quality inspection do you require?',
      recommendation_available: true,
      default_criticality: 'medium',
    },
    'quality.aql': {
      requirement: 'optional',
      label: 'AQL Standard',
      priority: 'high',
      layer: 'quality',
      question_template: 'Do you have a specific Acceptable Quality Limit (AQL) standard in mind?',
      recommendation_available: true,
      default_criticality: 'low',
      description: 'Never auto-invent AQL. Only record if buyer stated or AI recommended + approved.',
    },
    'quality.third_party_inspection': {
      requirement: 'optional',
      label: 'Third-Party Inspection',
      priority: 'high',
      layer: 'quality',
      options: ['yes', 'no', 'supplier_arranged'],
      recommendation_available: true,
      default_criticality: 'low',
    },
    'quality.sample_requirements': {
      requirement: 'optional',
      label: 'Sample Requirements',
      priority: 'medium',
      layer: 'quality',
      default_criticality: 'low',
    },

    // ─── SECTION E: COMMERCIAL ──────────────────────────────────────────
    'commercial.target_price': {
      requirement: 'optional',
      label: 'Target Unit Price',
      priority: 'high',
      layer: 'commercial',
      question_template: 'Do you have a target unit price in mind?',
      buyer_side: true,
      default_criticality: 'medium',
    },
    'commercial.currency': {
      requirement: 'optional',
      label: 'Currency',
      priority: 'medium',
      layer: 'commercial',
      default_criticality: 'low',
    },
    'commercial.supplier_moq': {
      requirement: 'optional',
      label: 'Supplier MOQ',
      priority: 'high',
      layer: 'commercial',
      buyer_side: false,
      default_criticality: 'supplier_dependent',
      description: 'Supplier minimum order quantity — distinct from buyer required quantity',
    },
    'commercial.payment_terms': {
      requirement: 'required',
      label: 'Payment Terms',
      priority: 'critical',
      layer: 'commercial',
      question_template: 'What are your preferred payment terms (e.g. 30% deposit / 70% T/T, L/C, Net 30)?',
      recommendation_available: true,
      default_criticality: 'critical',
    },
    'commercial.incoterm': {
      requirement: 'required',
      label: 'Incoterms',
      priority: 'critical',
      layer: 'commercial',
      question_template: 'What Incoterms do you prefer (e.g., FOB, EXW, DDP, CIF)?',
      recommendation_available: true,
      default_criticality: 'critical',
    },
    'commercial.quotation_validity': {
      requirement: 'optional',
      label: 'Quotation Validity',
      priority: 'low',
      layer: 'commercial',
      buyer_side: false,
      default_criticality: 'supplier_dependent',
    },
    'commercial.tooling_cost': {
      requirement: 'optional',
      label: 'Tooling / Setup Cost',
      priority: 'low',
      layer: 'commercial',
      buyer_side: false,
      default_criticality: 'supplier_dependent',
    },

    // ─── SECTION F: LOGISTICS & DELIVERY ────────────────────────────────
    'logistics.origin_country': {
      requirement: 'recommended',
      label: 'Origin Country',
      priority: 'high',
      layer: 'logistics',
      question_template: 'Do you have a preferred country of origin, or should we source globally?',
      recommendation_available: true,
      default_criticality: 'high',
      description: 'NEVER assume China or any country. Always ask.',
    },
    'logistics.destination_country': {
      requirement: 'required',
      label: 'Delivery Address / Destination Country',
      priority: 'critical',
      layer: 'logistics',
      question_template: 'What is your delivery address or destination country/city?',
      default_criticality: 'critical',
    },
    'logistics.destination_city': {
      requirement: 'optional',
      label: 'Destination City',
      priority: 'medium',
      layer: 'logistics',
      default_criticality: 'medium',
    },
    'logistics.destination_port': {
      requirement: 'optional',
      label: 'Destination Port',
      priority: 'low',
      layer: 'logistics',
      default_criticality: 'low',
    },
    'logistics.shipping_mode': {
      requirement: 'recommended',
      label: 'Shipping Mode',
      priority: 'high',
      layer: 'logistics',
      question_template: 'How do you plan to ship the goods (e.g., sea freight, air freight)?',
      recommendation_available: true,
      default_criticality: 'medium',
    },
    'logistics.required_arrival': {
      requirement: 'recommended',
      label: 'Required Delivery Date',
      priority: 'critical',
      layer: 'logistics',
      question_template: 'Do you have a strict deadline for when these need to arrive?',
      default_criticality: 'high',
    },
    'logistics.production_lead_time': {
      requirement: 'optional',
      label: 'Production Lead Time',
      priority: 'medium',
      layer: 'logistics',
      buyer_side: false,
      default_criticality: 'supplier_dependent',
    },

    // ─── SECTION G: PACKAGING ───────────────────────────────────────────
    'packaging.packaging_type': {
      requirement: 'recommended',
      label: 'Packaging Type',
      priority: 'high',
      layer: 'logistics',
      question_template: 'Do you have specific packaging requirements for retail or transit?',
      recommendation_available: true,
      default_criticality: 'medium',
    },
    'packaging.units_per_carton': {
      requirement: 'optional',
      label: 'Units per Carton',
      priority: 'medium',
      layer: 'logistics',
      default_criticality: 'low',
    },
    'packaging.carton_spec': {
      requirement: 'optional',
      label: 'Carton Specification',
      priority: 'low',
      layer: 'logistics',
      default_criticality: 'low',
    },
    'packaging.palletization': {
      requirement: 'optional',
      label: 'Palletization',
      priority: 'low',
      layer: 'logistics',
      default_criticality: 'low',
    },
    'packaging.protective_material': {
      requirement: 'optional',
      label: 'Protective Packaging',
      priority: 'medium',
      layer: 'logistics',
      default_criticality: 'low',
      criticality_rules: [
        { when: { 'specifications.material': ['ceramic', 'glass', 'porcelain', 'stoneware', 'bone china', 'earthenware'] }, criticality: 'high' }
      ],
    },
  },
};
