/**
 * Normalizes user-entered or extracted country names / codes to standard ISO3 codes.
 */
const COUNTRY_TO_ISO3: Record<string, string> = {
  // France & Europe
  france: 'FRA',
  fr: 'FRA',
  fra: 'FRA',
  germany: 'DEU',
  de: 'DEU',
  deu: 'DEU',
  deutschland: 'DEU',
  italy: 'ITA',
  it: 'ITA',
  ita: 'ITA',
  italia: 'ITA',
  spain: 'ESP',
  es: 'ESP',
  esp: 'ESP',
  espana: 'ESP',
  belgium: 'BEL',
  be: 'BEL',
  bel: 'BEL',
  netherlands: 'NLD',
  holland: 'NLD',
  nl: 'NLD',
  nld: 'NLD',
  poland: 'POL',
  pl: 'POL',
  pol: 'POL',
  portugal: 'PRT',
  pt: 'PRT',
  prt: 'PRT',
  switzerland: 'CHE',
  ch: 'CHE',
  che: 'CHE',
  austria: 'AUT',
  at: 'AUT',
  aut: 'AUT',
  sweden: 'SWE',
  se: 'SWE',
  swe: 'SWE',
  denmark: 'DNK',
  dk: 'DNK',
  dnk: 'DNK',
  norway: 'NOR',
  no: 'NOR',
  nor: 'NOR',
  finland: 'FIN',
  fi: 'FIN',
  fin: 'FIN',
  ireland: 'IRL',
  ie: 'IRL',
  irl: 'IRL',
  greece: 'GRC',
  gr: 'GRC',
  grc: 'GRC',
  czechia: 'CZE',
  'czech republic': 'CZE',
  cz: 'CZE',
  cze: 'CZE',
  hungary: 'HUN',
  hu: 'HUN',
  hun: 'HUN',
  romania: 'ROU',
  ro: 'ROU',
  rou: 'ROU',

  // Americas
  'united states': 'USA',
  usa: 'USA',
  us: 'USA',
  america: 'USA',
  canada: 'CAN',
  ca: 'CAN',
  can: 'CAN',
  mexico: 'MEX',
  mx: 'MEX',
  mex: 'MEX',
  brazil: 'BRA',
  br: 'BRA',
  bra: 'BRA',
  argentina: 'ARG',
  ar: 'ARG',
  arg: 'ARG',
  chile: 'CHL',
  cl: 'CHL',
  chl: 'CHL',
  colombia: 'COL',
  co: 'COL',
  col: 'COL',

  // Asia / Pacific
  china: 'CHN',
  cn: 'CHN',
  chn: 'CHN',
  prc: 'CHN',
  india: 'IND',
  in: 'IND',
  ind: 'IND',
  vietnam: 'VNM',
  'viet nam': 'VNM',
  vn: 'VNM',
  vnm: 'VNM',
  indonesia: 'IDN',
  id: 'IDN',
  idn: 'IDN',
  japan: 'JPN',
  jp: 'JPN',
  jpn: 'JPN',
  'south korea': 'KOR',
  korea: 'KOR',
  kr: 'KOR',
  kor: 'KOR',
  taiwan: 'TWN',
  tw: 'TWN',
  twn: 'TWN',
  thailand: 'THA',
  th: 'THA',
  tha: 'THA',
  malaysia: 'MYS',
  my: 'MYS',
  mys: 'MYS',
  singapore: 'SGP',
  sg: 'SGP',
  sgp: 'SGP',
  philippines: 'PHL',
  ph: 'PHL',
  phl: 'PHL',
  australia: 'AUS',
  au: 'AUS',
  aus: 'AUS',
  'new zealand': 'NZL',
  nz: 'NZL',
  nzl: 'NZL',

  // Middle East & Africa
  'united arab emirates': 'ARE',
  uae: 'ARE',
  ae: 'ARE',
  are: 'ARE',
  dubai: 'ARE',
  'saudi arabia': 'SAU',
  sa: 'SAU',
  sau: 'SAU',
  ksa: 'SAU',
  turkey: 'TUR',
  turkiye: 'TUR',
  tr: 'TUR',
  tur: 'TUR',
  egypt: 'EGY',
  eg: 'EGY',
  egy: 'EGY',
  'south africa': 'ZAF',
  za: 'ZAF',
  zaf: 'ZAF',

  // UK
  'united kingdom': 'GBR',
  uk: 'GBR',
  gb: 'GBR',
  gbr: 'GBR',
  britain: 'GBR',
  england: 'GBR',
};

const ISO3_TO_COUNTRY: Record<string, string> = {
  FRA: 'France',
  DEU: 'Germany',
  ITA: 'Italy',
  ESP: 'Spain',
  BEL: 'Belgium',
  NLD: 'Netherlands',
  POL: 'Poland',
  PRT: 'Portugal',
  CHE: 'Switzerland',
  AUT: 'Austria',
  SWE: 'Sweden',
  DNK: 'Denmark',
  GBR: 'United Kingdom',
  USA: 'United States',
  CAN: 'Canada',
  MEX: 'Mexico',
  BRA: 'Brazil',
  CHN: 'China',
  IND: 'India',
  VNM: 'Vietnam',
  IDN: 'Indonesia',
  JPN: 'Japan',
  KOR: 'South Korea',
  TWN: 'Taiwan',
  THA: 'Thailand',
  MYS: 'Malaysia',
  SGP: 'Singapore',
  AUS: 'Australia',
  ARE: 'United Arab Emirates',
  SAU: 'Saudi Arabia',
  TUR: 'Turkey',
};

export function normalizeCountryISO(input?: string): string {
  if (!input) return 'FRA';
  const clean = input.trim().toLowerCase().replace(/[.,/#!$%^&*;:{}=\-_`~()]/g, '');
  if (COUNTRY_TO_ISO3[clean]) {
    return COUNTRY_TO_ISO3[clean];
  }
  const upper = input.trim().toUpperCase();
  if (upper.length === 3) {
    return upper;
  }
  return COUNTRY_TO_ISO3[clean] || upper.slice(0, 3);
}

export function getCountryDisplayName(iso3: string): string {
  const upper = iso3.toUpperCase();
  return ISO3_TO_COUNTRY[upper] || upper;
}
